### ISSUE TITLE
The Hentaigana Font will be named "Noto Sans Kana or Noto Serif Kana?".

### ISSUE THREAD

**Issue by AshtonTameirao25** [notofonts/hentaigana#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fitojb** [comment]
"Sans" and "Serif" don't make much sense in the context of kana; Song and Mincho are better terms

**Comment by simoncozens** [comment]
That is true, but they make sense in the context of Noto - we (almost) invariably use "sans" to mean "unmodulated style" and "serif" to mean "modulated style", and so while it is not technically *ideal*, it is the most *helpful* approach as it helps users to know which fonts to use together.

So this will be Noto Serif Hentaigana.
